title: 'gishoo.github.io'
description: "An Engineer who loves to hack."
baseurl: ""
url: 

header_pages:
  - index.md
  - about.md
  - contact.md
  - portfolio.md

style: dark

footer: 'follow me on <a href="https://github.com/">github</a>'
#footer: 'follow us on <a href="https://twitter.com/">twitter</a>'

# Build settings
markdown: kramdown
remote_theme: b2a3e8/jekyll-theme-console
